# Generated by Django 3.0.3 on 2020-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetial',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('blog_img', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
